version: "2.3"

services:
  rest-villains:
    image: quarkus/faktorial
    container_name: "faktorial"
    mem_limit: 128m
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://quarkus-db:5432/nano
    ports:
      - "8080:8080"  # the HTTP endpoint
    depends_on:
      quarkus-db:
        condition: service_healthy
    networks:
      - quarkus

  quarkus-db:
    image: "postgres:14.6"
    mem_limit: 128m
    environment:
      - POSTGRES_USER=nano
      - POSTGRES_PASSWORD=nanonano
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nano"]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - "5433:5432"
    networks:
      - quarkus

networks:
  quarkus:
    driver: bridge

